# Generated by Django 6.0.1 on 2026-03-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(db_column='id_document', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
    ]
