# Generated by Django 6.0.1 on 2026-03-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('user', '0002_myuser_created_at_myuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_documents', to='user.myuser'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.myuser'),
        ),
        migrations.CreateModel(
            name='ShareDocument',
            fields=[
                ('id', models.AutoField(db_column='id_share_document', primary_key=True, serialize=False)),
                ('shared_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('id_document', models.ForeignKey(db_column='id_document', on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents_received', to='user.myuser')),
                ('shared_by', models.ForeignKey(db_column='shared_by', on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents_sent', to='user.myuser')),
            ],
            options={
                'verbose_name': 'Share Document',
                'verbose_name_plural': 'Share Documents',
                'db_table': 'share_documents',
            },
        ),
    ]
