# Generated by Django 5.2 on 2026-03-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_content_document_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
