# Generated by Django 6.0.1 on 2026-03-04 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_myuser_created_at_myuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(db_column='id_action_log', primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField()),
                ('action', models.TextField()),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
            options={
                'verbose_name': 'ActionLog',
                'verbose_name_plural': 'ActionLogs',
                'db_table': 'action_logs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='id_notification', primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_date', models.DateField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(db_column='id_saved_search', primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('search_date', models.DateField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
            options={
                'verbose_name': 'SavedSearch',
                'verbose_name_plural': 'SavedSearches',
                'db_table': 'saved_searches',
            },
        ),
    ]
