# Generated by Django 5.2.3 on 2026-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
