# Generated by Django 6.0.1 on 2026-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
            ],
            options={
                'verbose_name': 'MyUser',
                'verbose_name_plural': 'MyUsers',
                'db_table': 'users',
            },
        ),
    ]
