# Generated by Django 6.0.1 on 2026-03-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
